version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: jsguru
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: guru
    networks:
      - jsGuruNetwork
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: jsgurutest
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: guru
    networks:
      - jsGuruNetwork
networks:
  jsGuruNetwork: